version: '3'
services:

  mongodb:
    image: mongo:3.2
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=eas
    volumes:
      - egg-mongo:/data/db
      - ./init.d/mongo:/docker-entrypoint-initdb.d
    networks:
      - docker_eas
    ports:
      - 27017:27017

  eas:
    image: daocloud.io/xjchenhao/eas
    environment:
      - NODE_ENV=test
      - EGG_SERVER_ENV=test
    depends_on:
      - mongodb
    networks:
      - docker_eas
    ports:
      - 7001:7001

volumes:
  egg-mongo:

networks:
  docker_eas:
    driver: bridge