version: '3'
services:

  mongodb:
    image: mongo:3.2
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=eas
    volumes:
      - ./db:/data/db
      - ./init.d/mongo:/docker-entrypoint-initdb.d
    networks:
      - docker_eas
    ports:
      - 27017:27017

networks:
  docker_eas:
    driver: bridge